### ISSUE TITLE
Consider adding a default box-sizing

### ISSUE THREAD

**Issue by trst** [mattbirchler/birchtree-css#1]
https://github.com/mattbirchler/birchtree-css/blob/2fe54d08e25ae01ec759ec16e421f3a5f418a6fb/birchtree.css#L2

Have you thought about adding `box-sizing: border-box;` for a more predictable sizing method?

```css
*,
*::before,
*::after {
  box-sizing: border-box;
}
```

[More info via CSS-Tricks](https://css-tricks.com/box-sizing/)

****

Sorry there’s no pull request. In the spirit of the project I’m using my phone 😉
